name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Adăugarea explicită a pașilor pentru setup-ul Node.js și instalarea dependențelor
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # sau orice altă versiune specifică necesară proiectului tău

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RESTASIBIU }}'
          channelId: your-channel-id # Decomentează și înlocuiește cu ID-ul canalului dacă faci deploy într-un canal de preview
          projectId: restasibiu
